language: csharp
solution: OpenTween.sln

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - xbuild /p:Configuration=Debug /verbosity:quiet
  - mono ./packages/xunit.runner.console.2.1.0/tools/xunit.console.exe ./OpenTween.Tests/bin/Debug/OpenTween.Tests.dll -noappdomain
