version: 1.3.2.{build}

os: Visual Studio 2015

assembly_info:
  patch: true
  file: OpenTween\Properties\AssemblyInfo.cs
  assembly_file_version: '{version}'

build:
  project: OpenTween.sln
  verbosity: minimal

cache:
  - ./packages/

before_build:
  - nuget restore

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

test_script:
  - .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -target:".\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:".\OpenTween.Tests\bin\Debug\OpenTween.Tests.dll -noshadow -appveyor" -register:user -filter:"+[OpenTween*]* -[OpenTween.Tests]*" -excludebyfile:"*.Designer.cs" -skipautoprops -hideskipped:All -returntargetcode -output:coverage.xml

after_test:
  - npm install codecov --save
  - ./node_modules/.bin/codecov -f coverage.xml

  - del %APPVEYOR_BUILD_FOLDER%\OpenTween\bin\Debug\OpenTween.pdb
  - 7z a OpenTween_dev-%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\OpenTween\bin\Debug\*

artifacts:
  - name: OpenTween.zip
    path: OpenTween_dev-$(APPVEYOR_BUILD_NUMBER).zip

# vim: et fenc=utf-8 sts=2 sw=2 ts=2
